name: Deploy Preview to Vercel

on:
  workflow_call:
    inputs:
      vercel_env:
        description: 'Vercel environment to deploy to'
        required: true
        default: 'preview'
        type: string

    secrets:
      vercel_project_id:
        description: 'Vercel project ID'
        required: true
      vercel_token:
        description: 'Vercel token to use for deployment'
        required: true
      vercel_org_id:
        description: 'Vercel organization ID'
        required: true

jobs:
  deploy-preview:
    name: Deploy Preview
    runs-on: ubuntu-latest
    env:
      VERCEL_PROJECT_ID: ${{ secrets.vercel_project_id }}
      VERCEL_ORG_ID: ${{ secrets.vercel_org_id }}
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        name: Install pnpm
        id: pnpm-install
        with:
          version: 8
          run_install: false
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'pnpm'
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=${{ inputs.vercel_env }} --token=${{ secrets.vercel_token }}
      - name: Build Project Artifacts
        run: vercel build --token=${{ secrets.vercel_token }}
      - id: deploy-preview
        name: Deploy Project Artifacts to Vercel
        run: |
          url="$(vercel deploy --prebuilt --token=${{ secrets.vercel_token }})"
          echo "preview_url=$url" >> $GITHUB_OUTPUT
      - name: Get Current Pull Request
        uses: 8BitJonny/gh-get-current-pr@2.2.0
        id: pr
        with:
          sha: ${{ github.event.pull_request.head.sha }}
      - name: Comment Preview URL
        uses: thollander/actions-comment-pull-request@v2
        if: success() && github.event_name == 'pull_request'
        with:
          message: |
            Preview is deployed :rocket:

            **Preview URL:** [${{ steps.deploy-preview.outputs.preview_url }}](${{ steps.deploy-preview.outputs.preview_url }})
          reactions: rocket, eyes
          comment_tag: preview_url
          pr_number: ${{ steps.pr.outputs.number }}
      - name: Update job summary
        run: |
          echo "# Deploy Preview :rocket:" >> $GITHUB_STEP_SUMMARY
          echo "**Preview URL:** [${{ steps.deploy-preview.outputs.preview_url }}](${{ steps.deploy-preview.outputs.preview_url }}) " >> $GITHUB_STEP_SUMMARY
